#ifndef COMMON_RKHV_PAGING_H
#define COMMON_RKHV_PAGING_H

#define PAGE_SIZE 0x1000

#define LINEAR_ADDRESS_PML4_MASK   0x0000ff8000000000
#define LINEAR_ADDRESS_DP_MASK     0x0000007fc0000000
#define LINEAR_ADDRESS_D_MASK      0x000000003fe00000
#define LINEAR_ADDRESS_TABLE_MASK  0x00000000001ff000
#define LINEAR_ADDRESS_OFFSET_MASK 0x0000000000000fff

#define LINEAR_ADDRESS_PML4_SHIFT   39
#define LINEAR_ADDRESS_DP_SHIFT     30
#define LINEAR_ADDRESS_D_SHIFT      21
#define LINEAR_ADDRESS_TABLE_SHIFT  12
#define LINEAR_ADDRESS_OFFSET_SHIFT 0

#define LINEAR_ADDRESS_GET_PML4(x)          (((x)&LINEAR_ADDRESS_PML4_MASK) >> LINEAR_ADDRESS_PML4_SHIFT)
#define LINEAR_ADDRESS_GET_DIRECTORY_PTR(x) (((x)&LINEAR_ADDRESS_DP_MASK) >> LINEAR_ADDRESS_DP_SHIFT)
#define LINEAR_ADDRESS_GET_DIRECTORY(x)     (((x)&LINEAR_ADDRESS_D_MASK) >> LINEAR_ADDRESS_D_SHIFT)
#define LINEAR_ADDRESS_GET_TABLE(x)         (((x)&LINEAR_ADDRESS_TABLE_MASK) >> LINEAR_ADDRESS_TABLE_SHIFT)
#define LINEAR_ADDRESS_GET_OFFSET(x)        (((x)&LINEAR_ADDRESS_OFFSET_MASK) >> LINEAR_ADDRESS_OFFSET_SHIFT)

// PML4E : PML4 Entry
#define PML4E_PRESENT                  PTE_PRESENT
#define PML4E_READ_WRITE               PTE_READ_WRITE
#define PML4E_USER_SUPERVISOR          PTE_USER_SUPERVISOR
#define PML4E_PAGE_LEVEL_WRITE_THROUGH PTE_PAGE_LEVEL_WRITE_THROUGH
#define PML4E_PAGE_LEVEL_CACHE_DISABLE PTE_PAGE_LEVEL_CACHE_DISABLE
#define PML4E_ACCESSED                 PTE_ACCESSED
#define PML4E_PHYSICAL_ADDRESS_PDPT    PTE_PHYSICAL_ADDRESS_PAGE
#define PML4E_EXECUTE_DISABLE          PTE_EXECUTE_DISABLE

// PDPTE : Page-Directory-Pointer-Table Entry
#define PDPTE_PRESENT                  PTE_PRESENT
#define PDPTE_READ_WRITE               PTE_READ_WRITE
#define PDPTE_USER_SUPERVISOR          PTE_USER_SUPERVISOR
#define PDPTE_PAGE_LEVEL_WRITE_THROUGH PTE_PAGE_LEVEL_WRITE_THROUGH
#define PDPTE_PAGE_LEVEL_CACHE_DISABLE PTE_PAGE_LEVEL_CACHE_DISABLE
#define PDPTE_ACCESSED                 PTE_ACCESSED
#define PDPTE_PAGE_SIZE                PDE_PAGE_SIZE
#define PDPTE_EXECUTE_DISABLE          PTE_EXECUTE_DISABLE
// When PDPTE_PAGE_SIZE = 1
#define PDPTE_DIRTY                    PTE_DIRTY
#define PDPTE_GLOBAL                   PTE_GLOBAL
#define PDPTE_PAGE_ATTRIBUTE_TABLE     PDE_PAGE_ATTRIBUTE_TABLE
#define PDPTE_PHYSICAL_ADDRESS_PAGE    0x000fffffc0000000
// When PDPTE_PAGE_SIZE = 0
#define PDPTE_PHYSICAL_ADDRESS_PD      PTE_PHYSICAL_ADDRESS_PAGE

// PDE : Page-Directory Entry
#define PDE_PRESENT                  PTE_PRESENT
#define PDE_READ_WRITE               PTE_READ_WRITE
#define PDE_USER_SUPERVISOR          PTE_USER_SUPERVISOR
#define PDE_PAGE_LEVEL_WRITE_THROUGH PTE_PAGE_LEVEL_WRITE_THROUGH
#define PDE_PAGE_LEVEL_CACHE_DISABLE PTE_PAGE_LEVEL_CACHE_DISABLE
#define PDE_ACCESSED                 PTE_ACCESSED
#define PDE_PAGE_SIZE                0x0000000000000080
#define PDE_EXECUTE_DISABLE          PTE_EXECUTE_DISABLE
// When PDE_PAGE_SIZE = 1
#define PDE_DIRTY                    PTE_DIRTY
#define PDE_GLOBAL                   PTE_GLOBAL
#define PDE_PAGE_ATTRIBUTE_TABLE     0x0000000000001000
#define PDE_PHYSICAL_ADDRESS_PAGE    0x000fffffffe00000
// When PDE_PAGE_SIZE = 0
#define PDE_PHYSICAL_ADDRESS_PT      PTE_PHYSICAL_ADDRESS_PAGE

// PTE : Page-Table Entry
#define PTE_PRESENT                  0x0000000000000001
#define PTE_READ_WRITE               0x0000000000000002
#define PTE_USER_SUPERVISOR          0x0000000000000004
#define PTE_PAGE_LEVEL_WRITE_THROUGH 0x0000000000000008
#define PTE_PAGE_LEVEL_CACHE_DISABLE 0x0000000000000010
#define PTE_ACCESSED                 0x0000000000000020
#define PTE_DIRTY                    0x0000000000000040
#define PTE_PAGE_ATTRIBUTE_TABLE     0x0000000000000080
#define PTE_GLOBAL                   0x0000000000000100
#define PTE_PHYSICAL_ADDRESS_PAGE    0x000ffffffffff000
#define PTE_EXECUTE_DISABLE          0x8000000000000000

#endif
