#ifndef VMX_EPT
#define VMX_EPT

#include <rkhv/paging.h>
#include <rkhv/stdint.h>

#define GUEST_PHYSICAL_ADDRESS_PML4_MASK   LINEAR_ADDRESS_PML4_MASK
#define GUEST_PHYSICAL_ADDRESS_DP_MASK     LINEAR_ADDRESS_DP_MASK
#define GUEST_PHYSICAL_ADDRESS_D_MASK      LINEAR_ADDRESS_D_MASK
#define GUEST_PHYSICAL_ADDRESS_TABLE_MASK  LINEAR_ADDRESS_TABLE_MASK
#define GUEST_PHYSICAL_ADDRESS_OFFSET_MASK LINEAR_ADDRESS_OFFSET_MASK

#define GUEST_PHYSICAL_ADDRESS_PML4_SHIFT   LINEAR_ADDRESS_PML4_SHIFT
#define GUEST_PHYSICAL_ADDRESS_DP_SHIFT     LINEAR_ADDRESS_DP_SHIFT
#define GUEST_PHYSICAL_ADDRESS_D_SHIFT      LINEAR_ADDRESS_D_SHIFT
#define GUEST_PHYSICAL_ADDRESS_TABLE_SHIFT  LINEAR_ADDRESS_TABLE_SHIFT
#define GUEST_PHYSICAL_ADDRESS_OFFSET_SHIFT LINEAR_ADDRESS_OFFSET_SHIFT

#define GUEST_PHYSICAL_ADDRESS_GET_PML4(x)          (((x)&GUEST_PHYSICAL_ADDRESS_PML4_MASK) >> GUEST_PHYSICAL_ADDRESS_PML4_SHIFT)
#define GUEST_PHYSICAL_ADDRESS_GET_DIRECTORY_PTR(x) (((x)&GUEST_PHYSICAL_ADDRESS_DP_MASK) >> GUEST_PHYSICAL_ADDRESS_DP_SHIFT)
#define GUEST_PHYSICAL_ADDRESS_GET_DIRECTORY(x)     (((x)&GUEST_PHYSICAL_ADDRESS_D_MASK) >> GUEST_PHYSICAL_ADDRESS_D_SHIFT)
#define GUEST_PHYSICAL_ADDRESS_GET_TABLE(x)         (((x)&GUEST_PHYSICAL_ADDRESS_TABLE_MASK) >> GUEST_PHYSICAL_ADDRESS_TABLE_SHIFT)
#define GUEST_PHYSICAL_ADDRESS_GET_OFFSET(x)        (((x)&GUEST_PHYSICAL_ADDRESS_OFFSET_MASK) >> GUEST_PHYSICAL_ADDRESS_OFFSET_SHIFT)

// EPT PML4E : PML4 Entry
#define EPT_PML4E_READ                  EPT_PTE_READ
#define EPT_PML4E_WRITE                 EPT_PTE_WRITE
#define EPT_PML4E_EXECUTE               EPT_PTE_EXECUTE
#define EPT_PML4E_EXECUTE_SUPERVISOR    EPT_PTE_EXECUTE_SUPERVISOR
#define EPT_PML4E_ACCESSED              EPT_PTE_ACCESSED
#define EPT_PML4E_EXECUTE_USER          EPT_PTE_EXECUTE_USER
#define EPT_PML4E_PHYSICAL_ADDRESS_PDPT EPT_PTE_PHYSICAL_ADDRESS_PAGE
#define EPT_PML4E_SUPPRESS_VE           EPT_PTE_SUPPRESS_VE

// EPT PDPTE : Page-Directory-Pointer-Table Entry
#define EPT_PDPTE_READ                    EPT_PTE_READ
#define EPT_PDPTE_WRITE                   EPT_PTE_WRITE
#define EPT_PDPTE_EXECUTE                 EPT_PTE_EXECUTE
#define EPT_PDPTE_EXECUTE_SUPERVISOR      EPT_PTE_EXECUTE_SUPERVISOR
#define EPT_PDPTE_PAGE_SIZE               EPT_PDE_PAGE_SIZE
#define EPT_PDPTE_ACCESSED                EPT_PTE_ACCESSED
#define EPT_PDPTE_EXECUTE_USER            EPT_PTE_EXECUTE_USER
#define EPT_PDPTE_SUPPRESS_VE             EPT_PTE_SUPPRESS_VE
// When EPT_PDPTE_PAGE_SIZE = 1
#define EPT_PDPTE_MEMORY_TYPE             EPT_PTE_MEMORY_TYPE
#define EPT_PDPTE_IGNORE_PAT_MEMORY_TYPE  EPT_PTE_IGNORE_PAT_MEMORY_TYPE
#define EPT_PDPTE_WRITTEN                 EPT_PTE_WRITTEN
#define EPT_PDPTE_PHYSICAL_ADDRESS_PAGE   0x000fffffc0000000
#define EPT_PDPTE_VERIFY_GUEST_PAGING     EPT_PTE_VERIFY_GUEST_PAGING
#define EPT_PDPTE_PAGING_WRITE            EPT_PTE_PAGING_WRITE
#define EPT_PDPTE_SUPERVISOR_SHADOW_STACK EPT_PTE_SUPERVISOR_SHADOW_STACK
// When EPT_PDPTE_PAGE_SIZE = 0
#define EPT_PDPTE_PHYSICAL_ADDRESS_PD     EPT_PTE_PHYSICAL_ADDRESS_PAGE

// EPT PDE : Page-Directory Entry
#define EPT_PDE_READ                    EPT_PTE_READ
#define EPT_PDE_WRITE                   EPT_PTE_WRITE
#define EPT_PDE_EXECUTE                 EPT_PTE_EXECUTE
#define EPT_PDE_EXECUTE_SUPERVISOR      EPT_PTE_EXECUTE_SUPERVISOR
#define EPT_PDE_PAGE_SIZE               0x0000000000000080
#define EPT_PDE_ACCESSED                EPT_PTE_ACCESSED
#define EPT_PDE_EXECUTE_USER            EPT_PTE_EXECUTE_USER
#define EPT_PDE_SUPPRESS_VE             EPT_PTE_SUPPRESS_VE
// When EPT_PDE_PAGE_SIZE = 1
#define EPT_PDE_MEMORY_TYPE             EPT_PTE_MEMORY_TYPE
#define EPT_PDE_IGNORE_PAT_MEMORY_TYPE  EPT_PTE_IGNORE_PAT_MEMORY_TYPE
#define EPT_PDE_WRITTEN                 EPT_PTE_WRITTEN
#define EPT_PDE_PHYSICAL_ADDRESS_PAGE   0x000fffffffe00000
#define EPT_PDE_VERIFY_GUEST_PAGING     EPT_PTE_VERIFY_GUEST_PAGING
#define EPT_PDE_PAGING_WRITE            EPT_PTE_PAGING_WRITE
#define EPT_PDE_SUPERVISOR_SHADOW_STACK EPT_PTE_SUPERVISOR_SHADOW_STACK
// When EPT_PDE_PAGE_SIZE = 0
#define EPT_PDE_PHYSICAL_ADDRESS_PT     EPT_PTE_PHYSICAL_ADDRESS_PAGE

// EPT PTE : Page-Table Entry
#define EPT_PTE_READ                      0x0000000000000001
#define EPT_PTE_WRITE                     0x0000000000000002
#define EPT_PTE_EXECUTE                   0x0000000000000004
#define EPT_PTE_EXECUTE_SUPERVISOR        EPT_PTE_EXECUTE
#define EPT_PTE_MEMORY_TYPE               0x0000000000000038
#define EPT_PTE_IGNORE_PAT_MEMORY_TYPE    0x0000000000000040
#define EPT_PTE_ACCESSED                  0x0000000000000100
#define EPT_PTE_WRITTEN                   0x0000000000000200
#define EPT_PTE_EXECUTE_USER              0x0000000000000400
#define EPT_PTE_PHYSICAL_ADDRESS_PAGE     0x000ffffffffff000
#define EPT_PTE_VERIFY_GUEST_PAGING       0x0200000000000000
#define EPT_PTE_PAGING_WRITE              0x0400000000000000
#define EPT_PTE_SUPERVISOR_SHADOW_STACK   0x1000000000000000
#define EPT_PTE_SUBPAGE_WRITE_PERMISSIONS 0x2000000000000000
#define EPT_PTE_SUPPRESS_VE               0x8000000000000000

uintptr_t vmx_ept_create_transparent(void);

#endif
